### ISSUE TITLE
Fans are shown as not available

### ISSUE THREAD

**Issue by gondhijagapathi** [dasshubham762/atomberg-integration#11]
## System Information

version | core-2024.5.5
-- | --
installation_type | Home Assistant Container
dev | false
hassio | false
docker | true
user | root
virtualenv | false
python_version | 3.12.2
os_name | Linux
os_version | 5.15.0-107-generic
arch | x86_64
timezone | Asia/Calcutta
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4972
Installed Version | 1.34.0
Stage | running
Available Repositories | 1393
Downloaded Repositories | 2
HACS Data | ok

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 0
views | 0
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | June 4, 2024 at 7:28 PM
-- | --
current_recorder_run | June 5, 2024 at 10:27 PM
estimated_db_size | 2.55 MiB
database_engine | sqlite
database_version | 3.44.2

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

Fans Shown as unavailable after completing adding api keys and refresh token

![image](https://github.com/dasshubham762/atomberg-integration/assets/23327757/a3e724c4-395f-413e-855d-9d643670cac3)

### Reproduction steps

1. followed instructions from readme , thats it
2.
3.
...

### Debug logs

```text
nb jj
```

**Comment by gondhijagapathi** [comment]
NVM, i solved the issue , i see we need 5625 port on home assistant system to be open , (I have UFW firewall)

`sudo ufw allow 5625`

above command solved my issue

**Comment by vsnthdev** [comment]
I'm also getting the same error, don't know why. Tried unlocking port 5625 from my Home Assistant Docker container to the host machine (which doesn't have a firewall) but sill my fans shows up as "Unavailable".

Any idea what could be causing it @gondhijagapathi and @dasshubham762 🤔

**Comment by dasshubham762** [comment]
@vsnthdev Try setting network_mode as host for the HA container.

**Comment by vsnthdev** [comment]
Thank you so much for building this @dasshubham762 I have added my first ever fan to HA 🙌

I previously had my ports exposed in the following way 👇

```yml
ports:
  - 8123:8123
  - "5625:5625"
  - "6666:6666/udp"
  - "6667:6667/udp"
```

And I replaced `"5625:5625"` with `"5625:5625/udp"` and it started to work ✅
