### ISSUE TITLE
API Rate Limited

### ISSUE THREAD

**Issue by tanishqmanuja** [dasshubham762/atomberg-integration#13]
Atomberg has rate limited the public API, So most of the time my HA Dashboard looks like this (image below)
![image](https://github.com/dasshubham762/atomberg-integration/assets/40914272/271e56fc-9190-4bb3-9122-ef49c20f5151)

Do you know any follow up on this from Atomberg, have you mailed them regarding this ?

PS:
I Mailed Atomberg regarding HA Integration and they said they are working on it, and provided me this repo link as a workaround until then. But now this integration is not that useful due to the rate limit. Maybe we could use push based logic in the integration rather than polling to save quota ?

![image](https://github.com/dasshubham762/atomberg-integration/assets/40914272/3b205735-e286-4a58-ba2a-60917fe37b54)

**Comment by dasshubham762** [comment]
Restarting HA fixes the issue?

**Comment by tanishqmanuja** [comment]
Nope

**Comment by tanishqmanuja** [comment]
The limit is 100 calls a day!

By simple math, if the integration uses a polling interval of 15s per device

In my case:
Number of devices = 2
Max calls per device = 100/2 = 50 requests
Max Active Time per device = 50x15 = 750 seconds = 12.5 minutes

So 12.5 mins per day is what we expect per day

**Comment by dasshubham762** [comment]
It does not work like that. It sends a request initially to get the list of devices and then uses API calls to only send commands. 
It does not use polling. It receives status updates through UDP locally.

**Comment by dasshubham762** [comment]
Btw, do you have HA and Fans on the same network?

**Comment by tanishqmanuja** [comment]
Ohh mb, If this doesnt use polling via http .. then limit shouldn't be a problem.

> Btw, do you have HA and Fans on the same network?

Yes I have them on same network, Maybe then I should debug UDP connection ?

**Comment by tanishqmanuja** [comment]
Docker Instance with network set to host

**Comment by dasshubham762** [comment]
`sudo ufw allow 5625`

Try running this command from terminal you have ufw installed

**Comment by tanishqmanuja** [comment]
Works now as expected .. i recently turned on firewall because I was exposing a ssh connection forgot to allow this UDP port though. Thanks a lot for the quick help 😁

**Comment by tanishqmanuja** [comment]
Maybe adding the port to the readme could be useful for future references just in case someone does the same as me. Also you can close this now

**Comment by dasshubham762** [comment]
Sure, I'll update the instructions.

Happy to help you.
