### ISSUE TITLE
All entities in Atomberg integration shows offline

### ISSUE THREAD

**Issue by lakshyarao22** [dasshubham762/atomberg-integration#19]
## System Information

version | core-2024.9.1
-- | --
installation_type | Home Assistant Container
dev | false
hassio | false
docker | true
user | root
virtualenv | false
python_version | 3.12.4
os_name | Linux
os_version | 6.9.12-3-MANJARO
arch | x86_64
timezone | Asia/Calcutta
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
HACS Data | ok
GitHub API Calls Remaining | 5000
Installed Version | 2.0.1
Stage | running
Available Repositories | 1411
Downloaded Repositories | 5

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 0
views | 0
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | September 15, 2024 at 11:12 AM
-- | --
current_recorder_run | September 19, 2024 at 9:38 AM
estimated_db_size | 6.23 MiB
database_engine | sqlite
database_version | 3.45.3

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

I have added api key and secret and able to setup entities but never able to get the fans online on home assistant.

### Reproduction steps

Add integration 
Enter api key and secret
Setup fans to there rooms
Unable to control them as it shows offline

### Debug logs

```text
Logger: homeassistant.components.fan
Source: components/fan/__init__.py:295
integration: Fan (documentation, issues)
First occurred: 9:38:10 AM (12 occurrences)
Last logged: 9:38:10 AM

Entity None (<class 'custom_components.atomberg.fan.AtombergFanEntity'>) does not set FanEntityFeature.TURN_OFF but implements the turn_off method. Please create a bug report at https://github.com/dasshubham762/atomberg-integration/issues
Entity None (<class 'custom_components.atomberg.fan.AtombergFanEntity'>) does not set FanEntityFeature.TURN_ON but implements the turn_on method. Please create a bug report at https://github.com/dasshubham762/atomberg-integration/issues
```

**Comment by dasshubham762** [comment]
Thanks for reporting. Will look into and get back to you.

**Comment by dasshubham762** [comment]
Make sure you are running the container with `network_mode` set to `host` and port `5625` is not used by another app or blocked by firewall.

**Comment by lakshyarao22** [comment]
Hi,
I was using runtipi to host homeassistant and now i have installed it on my own ( including network mode as host) and now its working

Thank you so much

**Comment by LuigiBaron** [comment]
I have the same issue HAOS installed on proxmox..
