### ISSUE TITLE
Renesa fan showing unavailable on Home assistant

### ISSUE THREAD

**Issue by shivendra1401** [dasshubham762/atomberg-integration#21]
## System Information

version | core-2024.9.3
-- | --
installation_type | Unsupported Third Party Container
dev | false
hassio | false
docker | true
user | abc
virtualenv | false
python_version | 3.12.4
os_name | Linux
os_version | 6.6.31+rpt-rpi-2712
arch | aarch64
timezone | Asia/Calcutta
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
HACS Data | ok
GitHub API Calls Remaining | 4989
Installed Version | 2.0.1
Stage | running
Available Repositories | 1435
Downloaded Repositories | 7

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Dashboards</summary>

dashboards | 4
-- | --
resources | 3
views | 3
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | September 30, 2024 at 6:48 PM
-- | --
current_recorder_run | October 10, 2024 at 2:35 PM
estimated_db_size | 34.97 MiB
database_engine | sqlite
database_version | 3.45.3

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

Renesa fan unavailable in integration

### Reproduction steps

1. Added custom integration for atomberg
2. detected renesa fan
3. all device and entitites unavailable
4. enabled debugged logs and only warning I can see added below
5. tried refreshing and restart of home assistant
...

### Debug logs

```text
2024-10-10 09:08:42.209 WARNING (MainThread) [homeassistant.components.fan] Entity None (<class 'custom_components.atomberg.fan.AtombergFanEntity'>) does not set FanEntityFeature.TURN_ON but implements the turn_on method.
```

**Comment by LuigiBaron** [comment]
I have the same issue..How did you resolve this?
