### ISSUE TITLE
Unable to configure

### ISSUE THREAD

**Issue by iyashwant** [dasshubham762/atomberg-integration#5]
## System Information

version | core-2024.3.0
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.2
os_name | Linux
os_version | 5.15.84-v8
arch | aarch64
timezone | Asia/Kolkata
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4862
Installed Version | 1.34.0
Stage | running
Available Repositories | 1401
Downloaded Repositories | 25

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 9.5
-- | --
update_channel | stable
supervisor_version | supervisor-2024.04.0
agent_version | 1.4.1
docker_version | 20.10.22
disk_total | 57.8 GB
disk_used | 11.8 GB
healthy | true
supported | true
board | rpi3-64
supervisor_api | ok
version_api | ok
installed_addons | Duck DNS (1.15.0), Samba share (12.3.0), File editor (5.8.0), Git pull (7.13.1), Terminal & SSH (9.9.0), Hey Ada! (1.1.1), Google Assistant SDK (2.5.0), Plex Media Server (3.5.0), OpenVPN Client (0.0.1), Grafana (9.1.3), Tautulli (4.0.1), Studio Code Server (5.15.0), Advanced SSH & Web Terminal (17.1.1), Node-RED (17.0.7)

</details>

<details><summary>Dashboards</summary>

dashboards | 6
-- | --
resources | 26
error | /config/ui-lovelace.yaml not found
views | 14
mode | yaml

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | February 29, 2024 at 10:45 PM
-- | --
current_recorder_run | April 22, 2024 at 11:00 PM
estimated_db_size | 7.55 MiB
database_engine | sqlite
database_version | 3.44.2

</details>

<details><summary>Sonoff</summary>

version | 3.6.0 (8dd8af9)
-- | --
cloud_online | 0 / 22
local_online | 0 / 0

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

After copying the folder to custom_components, it shows up in integrations, but clicking on it gives an error
"Error
Config flow could not be loaded: {"message":"Invalid handler specified"}"

![image](https://github.com/dasshubham762/atomberg-integration/assets/26032470/04f58390-456c-49bb-bb87-4cd39dcc99f3)

### Reproduction steps

1. Copy the folder into custom_components
2. Add integration from Settings page in UI
3. clicking on the atomberg in the list is giving the error
...

### Debug logs

```text
Logger: homeassistant.config_entries
Source: config_entries.py:2444
First occurred: 11:01:49 PM (6 occurrences)
Last logged: 11:23:26 PM

Error occurred loading flow for integration atomberg: cannot import name 'ConfigFlowResult' from 'homeassistant.config_entries' (/usr/src/homeassistant/homeassistant/config_entries.py)
```

**Comment by dasshubham762** [comment]
I have fixed the issue with the new release. Please check it out https://github.com/dasshubham762/atomberg-integration/releases/tag/v1.1.1
