### ISSUE TITLE
How to know the api_key and refresh_token. please add this info to the readme. 

### ISSUE THREAD

**Issue by prasunbheri** [dasshubham762/atomberg-integration#6]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

I have installed the integration and got to the point where it asks for api_key and refresh_token. I do not know how to get this info. Kindly add this info in the readme file

### Describe the solution you'd like

add the details on how to get api_key and refresh_token required to use the integration in the readme file.

### Describe alternatives you've considered

screenshots if applicable will be great. if it involves getting these details from mobile app in some way. 

### Additional context

any info related to getting api_key and refresh_token will be great.

**Comment by dasshubham762** [comment]
Updated installation and configuration instructions. Please check it out.
