### ISSUE TITLE
Fan unavailable

### ISSUE THREAD

**Issue by ashwinikalantri** [dasshubham762/atomberg-integration#8]
## System Information

version | core-2024.5.2
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.2
os_name | Linux
os_version | 6.6.28-haos-raspi
arch | aarch64
timezone | Asia/Calcutta
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4814
Installed Version | 1.34.0
Stage | running
Available Repositories | 1462
Downloaded Repositories | 21

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 12.3
-- | --
update_channel | stable
supervisor_version | supervisor-2024.05.1
agent_version | 1.6.0
docker_version | 25.0.5
disk_total | 57.8 GB
disk_used | 38.5 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Samba share (12.3.1), MariaDB (2.7.1), Home Assistant Google Drive Backup (0.112.1), Studio Code Server (5.15.0), Frigate Proxy (1.5), Node-RED (17.0.12), Cloudflared (5.1.9), chrony (3.0.1), ESPHome (2024.4.2), File editor (5.8.0), Advanced SSH & Web Terminal (17.2.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 13
views | 8
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 30 April 2024 at 1:07 PM
-- | --
current_recorder_run | 10 May 2024 at 7:40 PM
estimated_db_size | 14214.12 MiB
database_engine | mysql
database_version | 10.11.6

</details>

<details><summary>Sonoff</summary>

version | 3.7.3 (e240aaf)
-- | --
cloud_online | 5 / 6
local_online | 5 / 10
debug | failed to load: 

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

I have installed my first atomberg fan (Renesa Smart+). I was able to get the API Key and refresh token, install the integration and configure it. The integration detected the fan and its 5 entities. But all 5 entities are unavailable.

### Reproduction steps

1. Activated the developer account on the atom berg app and get the API key and refresh token.
2. Installed the integration from HACS, configured it with the API and refresh token
3. Integration detected the fan and its entities.
4. The state of the fan is always unavailable.
5. Restarting HA, reinstalling integration, disabling the device doesn't help.
6. I was able to fetch state and send commands on the Atomberg developer portal
...

### Debug logs

```text
The log file is here: 
https://drive.google.com/file/d/1XQ871Aew68t8QkkCX0wTFvI-oGAiGnu1/view?usp=share_link
```

### Diagnostics dump

Not available.

**Comment by dasshubham762** [comment]
The log file is too large. Can you provide a log file under 10 mb? (Just crop the required part)

**Comment by ashwinikalantri** [comment]
```
2024-05-12 15:11:04.571 WARNING (SyncWorker_6) [homeassistant.loader] We found a custom integration atomberg which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant

2024-05-13 10:35:05.672 DEBUG (MainThread) [custom_components.atomberg.udp_listener] Closed UDP listener on port 5625
2024-05-13 10:35:11.126 INFO (MainThread) [custom_components.atomberg.api] Found 1 atomberg devices
2024-05-13 10:35:11.139 DEBUG (MainThread) [custom_components.atomberg.udp_listener] Listening to broadcasts on UDP port 5625

2024-05-13 10:35:46.166 DEBUG (MainThread) [custom_components.atomberg.udp_listener] Closed UDP listener on port 5625

2024-05-13 10:36:12.196 INFO (MainThread) [custom_components.atomberg.api] Found 1 atomberg devices
2024-05-13 10:36:12.994 INFO (MainThread) [custom_components.atomberg.api] Found 1 atomberg devices
2024-05-13 10:36:13.008 DEBUG (MainThread) [custom_components.atomberg.udp_listener] Listening to broadcasts on UDP port 5625

```

**Comment by ashwinikalantri** [comment]
This is the new log file.
[home-assistant_atomberg_2024-05-13T05-06-29.792Z.log](https://github.com/dasshubham762/atomberg-integration/files/15289655/home-assistant_atomberg_2024-05-13T05-06-29.792Z.log)

**Comment by dasshubham762** [comment]
Do you have both the devices in same network?

**Comment by ashwinikalantri** [comment]
Yes, on the same network.

**Comment by ashwinikalantri** [comment]
Double checked and the fan and HA were not on the same network. Started working once correcting this.
